development:
  adapter: postgresql
  encoding: unicode
  database: catstagram_development
  pool: 5
  username:
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: catstagram_test
  pool: 5
  username:
  password:
  host: localhost


